[package]
name = "todomvc"
version = "0.1.0"
publish = false
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
tracing = "0.1.40"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["Storage", "Window"] }
xilem_web2 = { path = "../.." }
