[package]
name = "mathml_svg"
version = "0.1.0"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "mathml_svg"
test = false
doctest = false
doc = false
bench = false

[lints]
workspace = true

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
xilem_web = { path = "../.." }
