[package]
name = "todomvc"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.19"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
xilem_html = { path = "../.." }
