[package]
name = "raw_dom_access"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "raw_dom_access"
test = false
doctest = false
doc = false
bench = false

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.29"
web-sys = "0.3.83"
xilem_web = { path = "../.." }
