[package]
name = "todomvc"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "todomvc"
test = false
doctest = false
doc = false
bench = false

[lints]
workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.108"
web-sys = { version = "0.3.85", features = ["Storage", "Window"] }
xilem_web = { path = "../.." }
